# --- Begin inlined module: file_type_knowledge.py ---
from pathlib import PurePosixPath


def _entry(
    *,
    identifier: str,
    title: str,
    category: str,
    summary: str,
    purpose: str,
    openclaw_use: str,
    location: str,
    note: str,
    field_notes: list[str],
    cautions: list[str],
) -> dict[str, object]:
    return _reference_entry(
        identifier=identifier,
        panel_title="File Type Reference",
        title=title,
        category=category,
        summary=summary,
        purpose=purpose,
        openclaw_use=openclaw_use,
        location=location,
        note=note,
        field_notes=field_notes,
        cautions=cautions,
        sources=[],
    )


BASENAME_REFERENCES: dict[str, dict[str, object]] = {
    ".ds_store": _entry(
        identifier="basename_ds_store",
        title=".DS_Store",
        category="macos_metadata",
        summary="Finder metadata file created by macOS.",
        purpose="Stores folder view preferences such as icon positions, view mode, and other Finder-specific metadata.",
        openclaw_use="OpenClaw does not depend on this file. It is macOS workspace noise unless a user intentionally preserves Finder state.",
        location="Common on macOS inside folders viewed in Finder.",
        note="Usually safe to treat as incidental metadata rather than meaningful project content.",
        field_notes=[
            "Frequently appears in synced folders after browsing them in Finder.",
            "Often useful as a cleanup candidate in cross-platform repos.",
        ],
        cautions=[
            "Do not confuse it with application data. It is Finder state, not user-authored content.",
        ],
    ),
    ".gitignore": _entry(
        identifier="basename_gitignore",
        title=".gitignore",
        category="git_metadata",
        summary="Git ignore rules file.",
        purpose="Tells Git which files or paths should stay untracked.",
        openclaw_use="Not OpenClaw-specific, but highly relevant when interpreting untracked, ignored, or generated workspace files.",
        location="Repository roots or nested subdirectories.",
        note="Often explains why cache, build, or secret-like files appear locally but are not versioned.",
        field_notes=[
            "Nested `.gitignore` files can change behavior for only part of a tree.",
        ],
        cautions=[
            "Ignoring a file does not mean it is unimportant; it only means Git is configured not to track it.",
        ],
    ),
    ".gitattributes": _entry(
        identifier="basename_gitattributes",
        title=".gitattributes",
        category="git_metadata",
        summary="Git attributes file for line endings, filters, diff behavior, and merge rules.",
        purpose="Applies repository-level file handling policies beyond simple ignore rules.",
        openclaw_use="Not OpenClaw-specific, but can explain unusual diffing, line-ending behavior, or binary/text classification.",
        location="Repository roots or nested subdirectories.",
        note="Useful when the analyzer sees files that behave differently in Git than their extension suggests.",
        field_notes=[
            "Often used for line-ending normalization and custom diff drivers.",
        ],
        cautions=[
            "Can make Git treat a file as binary even if it looks text-like.",
        ],
    ),
    ".editorconfig": _entry(
        identifier="basename_editorconfig",
        title=".editorconfig",
        category="editor_config",
        summary="Editor formatting and whitespace conventions.",
        purpose="Defines indentation, line endings, charset, and trailing whitespace behavior across editors.",
        openclaw_use="Not OpenClaw-specific, but it explains workspace formatting conventions the agent may be expected to follow.",
        location="Repository roots or nested subdirectories.",
        note="Often complements prettier, biome, eslint, or language-specific formatters.",
        field_notes=[],
        cautions=[],
    ),
    ".env": _entry(
        identifier="basename_env",
        title=".env",
        category="config_secret",
        summary="Environment-variable file commonly used for local secrets and runtime configuration.",
        purpose="Stores key-value pairs loaded into a local environment by an app, script, or CLI.",
        openclaw_use="OpenClaw itself does not require a `.env`, but third-party skills and helper tools often do.",
        location="Project roots, app directories, or tool-specific folders.",
        note="High-signal file for review because it often contains tokens, API keys, or environment-specific config.",
        field_notes=[
            "Common in Node, Python, and CLI-based automation projects.",
        ],
        cautions=[
            "Treat as sensitive unless you have strong evidence it contains only non-secret defaults.",
        ],
    ),
    ".zshrc": _entry(
        identifier="basename_zshrc",
        title=".zshrc",
        category="shell_config",
        summary="Interactive shell startup config for zsh.",
        purpose="Configures aliases, PATH changes, prompt settings, environment variables, and shell behavior for zsh sessions.",
        openclaw_use="Not OpenClaw-specific, but very relevant if a local tool or skill depends on shell aliases or environment setup.",
        location="Usually in the user's home directory.",
        note="Common on macOS because zsh is the default shell.",
        field_notes=[],
        cautions=[
            "Do not assume settings here apply to non-interactive subprocesses unless explicitly sourced.",
        ],
    ),
    ".bashrc": _entry(
        identifier="basename_bashrc",
        title=".bashrc",
        category="shell_config",
        summary="Interactive shell startup config for bash.",
        purpose="Configures aliases, PATH changes, environment variables, and shell behavior for bash sessions.",
        openclaw_use="Useful when local CLI behavior differs from a clean non-interactive environment.",
        location="Usually in the user's home directory.",
        note="More common on Linux than macOS, though still encountered on macOS setups.",
        field_notes=[],
        cautions=[
            "Do not assume automation inherits these settings unless the shell is launched interactively or the file is sourced.",
        ],
    ),
    ".bash_profile": _entry(
        identifier="basename_bash_profile",
        title=".bash_profile",
        category="shell_config",
        summary="Login-shell startup config for bash.",
        purpose="Configures environment variables and shell behavior for login sessions before interactive bash use.",
        openclaw_use="Relevant when CLI behavior differs between GUI login sessions, SSH sessions, and non-login shells.",
        location="Usually in the user's home directory.",
        note="More common on macOS and older bash-centric setups than `.bashrc` alone.",
        field_notes=[],
        cautions=[
            "Many systems source `.bashrc` from here; if they diverge, shell behavior can become confusing.",
        ],
    ),
    ".profile": _entry(
        identifier="basename_profile",
        title=".profile",
        category="shell_config",
        summary="Portable login-shell profile.",
        purpose="Sets environment variables and startup behavior for POSIX-style login shells.",
        openclaw_use="Useful when a machine-wide or user-wide environment affects tools or automation.",
        location="Usually in the user's home directory.",
        note="Often a fallback when `.bash_profile` or `.zprofile` is absent.",
        field_notes=[],
        cautions=[],
    ),
    ".zprofile": _entry(
        identifier="basename_zprofile",
        title=".zprofile",
        category="shell_config",
        summary="Login-shell startup config for zsh.",
        purpose="Configures environment and startup behavior for zsh login sessions.",
        openclaw_use="Relevant on macOS where Terminal, iTerm, or launch agents may inherit login-shell state.",
        location="Usually in the user's home directory.",
        note="Often pairs with `.zshrc`, which handles interactive shell behavior.",
        field_notes=[],
        cautions=[],
    ),
    ".zshenv": _entry(
        identifier="basename_zshenv",
        title=".zshenv",
        category="shell_config",
        summary="Global zsh environment config loaded for nearly every zsh invocation.",
        purpose="Sets baseline environment variables and shell behavior before login or interactive hooks.",
        openclaw_use="High-signal when subprocesses launched through zsh behave differently from a clean environment.",
        location="Usually in the user's home directory.",
        note="Loaded more broadly than `.zshrc`, so mistakes here have wide effect.",
        field_notes=[],
        cautions=[
            "Heavy or side-effectful logic here can slow down or destabilize many shell invocations.",
        ],
    ),
    ".gitconfig": _entry(
        identifier="basename_gitconfig",
        title=".gitconfig",
        category="git_metadata",
        summary="User-level Git configuration file.",
        purpose="Defines defaults such as user identity, aliases, signing, merge tools, and diff behavior.",
        openclaw_use="Useful for understanding Git behavior observed during analysis or tool execution.",
        location="Usually in the user's home directory.",
        note="Global settings here can explain repository behavior that is not visible inside one repo.",
        field_notes=[],
        cautions=[],
    ),
    ".npmrc": _entry(
        identifier="basename_npmrc",
        title=".npmrc",
        category="package_config",
        summary="npm configuration file.",
        purpose="Configures package registries, auth tokens, install defaults, and cache behavior for npm.",
        openclaw_use="Relevant when a skill or helper tool depends on Node packages or private registries.",
        location="Project roots or the user's home directory.",
        note="Can contain registry credentials or machine-specific install behavior.",
        field_notes=[],
        cautions=[
            "Treat as sensitive if it contains auth tokens or private registry config.",
        ],
    ),
    ".nvmrc": _entry(
        identifier="basename_nvmrc",
        title=".nvmrc",
        category="package_config",
        summary="Node version pin for `nvm`-style toolchains.",
        purpose="Declares which Node.js version a project expects.",
        openclaw_use="Explains why a JavaScript-based skill or tool may require a specific runtime.",
        location="Project roots.",
        note="Often paired with `package.json`.",
        field_notes=[],
        cautions=[],
    ),
    ".python-version": _entry(
        identifier="basename_python_version",
        title=".python-version",
        category="package_config",
        summary="Python version pin used by pyenv and similar tools.",
        purpose="Declares which Python interpreter version a project expects.",
        openclaw_use="Useful when Python-based tools behave differently across environments.",
        location="Project roots or the user's home directory.",
        note="Often pairs with `pyproject.toml`, `requirements.txt`, or virtualenv tooling.",
        field_notes=[],
        cautions=[],
    ),
    ".tool-versions": _entry(
        identifier="basename_tool_versions",
        title=".tool-versions",
        category="package_config",
        summary="Runtime version manifest for asdf-style toolchains.",
        purpose="Pins versions for one or more developer tools such as Node, Python, Ruby, or Go.",
        openclaw_use="Explains why local tools or skills expect specific language/runtime versions.",
        location="Project roots or the user's home directory.",
        note="Can centralize multi-language version pins in one place.",
        field_notes=[],
        cautions=[],
    ),
    "package.json": _entry(
        identifier="basename_package_json",
        title="package.json",
        category="package_metadata",
        summary="Node.js package manifest.",
        purpose="Defines package metadata, dependencies, scripts, and runtime/tooling configuration for Node-based projects.",
        openclaw_use="Common in skill bundles or helper tools written in JavaScript/TypeScript.",
        location="Project roots or package directories.",
        note="High-signal file for understanding what a JavaScript-based folder is meant to do.",
        field_notes=[
            "Often paired with `package-lock.json`, `pnpm-lock.yaml`, or `yarn.lock`.",
        ],
        cautions=[
            "Dependency and script declarations can imply install-time or runtime behavior even if the folder is not currently active.",
        ],
    ),
    "package-lock.json": _entry(
        identifier="basename_package_lock_json",
        title="package-lock.json",
        category="lockfile",
        summary="Pinned npm dependency lockfile.",
        purpose="Locks exact dependency versions for reproducible Node installs.",
        openclaw_use="Not OpenClaw-specific, but common in Node-based tools and third-party skills.",
        location="Beside `package.json`.",
        note="Usually generated rather than hand-authored.",
        field_notes=[
            "Large size is normal because it records full dependency trees.",
        ],
        cautions=[
            "Treat as dependency state, not business logic.",
        ],
    ),
    "pnpm-lock.yaml": _entry(
        identifier="basename_pnpm_lock",
        title="pnpm-lock.yaml",
        category="lockfile",
        summary="Pinned pnpm dependency lockfile.",
        purpose="Locks exact package graph for pnpm installs.",
        openclaw_use="Common in modern JavaScript projects and some skill/tool bundles.",
        location="Beside `package.json`.",
        note="Usually machine-generated.",
        field_notes=[],
        cautions=[],
    ),
    "yarn.lock": _entry(
        identifier="basename_yarn_lock",
        title="yarn.lock",
        category="lockfile",
        summary="Pinned Yarn dependency lockfile.",
        purpose="Locks exact package graph for Yarn installs.",
        openclaw_use="Common in JavaScript projects and some skill/tool bundles.",
        location="Beside `package.json`.",
        note="Usually machine-generated.",
        field_notes=[],
        cautions=[],
    ),
    "requirements.txt": _entry(
        identifier="basename_requirements_txt",
        title="requirements.txt",
        category="package_metadata",
        summary="Python dependency manifest.",
        purpose="Lists Python packages to install into an environment.",
        openclaw_use="Common in Python-based tools or skills.",
        location="Project roots or app directories.",
        note="Useful for understanding whether a folder is a Python app, helper script bundle, or analysis tool.",
        field_notes=[],
        cautions=[],
    ),
    "pyproject.toml": _entry(
        identifier="basename_pyproject_toml",
        title="pyproject.toml",
        category="package_metadata",
        summary="Modern Python project metadata and tool configuration.",
        purpose="Defines build system metadata and often centralizes formatter, linter, and test settings.",
        openclaw_use="Common in Python-based tools, including this analyzer.",
        location="Project roots.",
        note="Often replaces or complements `setup.py`, `setup.cfg`, and `requirements.txt`.",
        field_notes=[],
        cautions=[],
    ),
    "poetry.lock": _entry(
        identifier="basename_poetry_lock",
        title="poetry.lock",
        category="lockfile",
        summary="Pinned Poetry dependency lockfile.",
        purpose="Locks exact Python dependency versions for Poetry-managed projects.",
        openclaw_use="Common in Python tools that prefer Poetry over raw `requirements.txt` management.",
        location="Beside `pyproject.toml`.",
        note="Usually machine-generated.",
        field_notes=[],
        cautions=[],
    ),
    "pipfile": _entry(
        identifier="basename_pipfile",
        title="Pipfile",
        category="package_metadata",
        summary="Python dependency manifest for Pipenv.",
        purpose="Declares Python package dependencies and interpreter constraints.",
        openclaw_use="Useful for identifying Pipenv-based Python tooling.",
        location="Project roots.",
        note="Often paired with `Pipfile.lock`.",
        field_notes=[],
        cautions=[],
    ),
    "pipfile.lock": _entry(
        identifier="basename_pipfile_lock",
        title="Pipfile.lock",
        category="lockfile",
        summary="Pinned Pipenv dependency lockfile.",
        purpose="Locks exact Python dependency versions for reproducible Pipenv installs.",
        openclaw_use="Usually generated dependency state rather than user-authored logic.",
        location="Beside `Pipfile`.",
        note="Common in Pipenv-managed Python projects.",
        field_notes=[],
        cautions=[],
    ),
    "setup.py": _entry(
        identifier="basename_setup_py",
        title="setup.py",
        category="package_metadata",
        summary="Legacy or hybrid Python package build script.",
        purpose="Defines package build/install behavior for setuptools-based Python projects.",
        openclaw_use="Still common in older Python tools and some editable install workflows.",
        location="Project roots.",
        note="Often complements or predates `pyproject.toml`.",
        field_notes=[],
        cautions=[],
    ),
    "setup.cfg": _entry(
        identifier="basename_setup_cfg",
        title="setup.cfg",
        category="package_metadata",
        summary="INI-style setuptools and tool configuration.",
        purpose="Stores Python packaging metadata and related tool configuration outside Python code.",
        openclaw_use="Common in Python projects that split packaging and tool config across multiple files.",
        location="Project roots.",
        note="Often appears alongside `setup.py` or `pyproject.toml`.",
        field_notes=[],
        cautions=[],
    ),
    "cargo.toml": _entry(
        identifier="basename_cargo_toml",
        title="Cargo.toml",
        category="package_metadata",
        summary="Rust package manifest.",
        purpose="Defines Rust crate metadata, dependencies, binaries, and workspace layout.",
        openclaw_use="Useful for identifying Rust-based tools or CLIs used by a workspace or skill.",
        location="Rust project roots.",
        note="Often paired with `Cargo.lock`.",
        field_notes=[],
        cautions=[],
    ),
    "cargo.lock": _entry(
        identifier="basename_cargo_lock",
        title="Cargo.lock",
        category="lockfile",
        summary="Pinned Rust dependency lockfile.",
        purpose="Locks exact crate versions for reproducible builds.",
        openclaw_use="Common in Rust tools bundled into developer workflows.",
        location="Beside `Cargo.toml`.",
        note="Usually machine-generated.",
        field_notes=[],
        cautions=[],
    ),
    "go.mod": _entry(
        identifier="basename_go_mod",
        title="go.mod",
        category="package_metadata",
        summary="Go module manifest.",
        purpose="Defines a Go module path, Go version, and direct dependency requirements.",
        openclaw_use="Useful for identifying Go-based CLIs or helpers in a workspace.",
        location="Go project roots.",
        note="Often paired with `go.sum`.",
        field_notes=[],
        cautions=[],
    ),
    "go.sum": _entry(
        identifier="basename_go_sum",
        title="go.sum",
        category="lockfile",
        summary="Go dependency checksum lockfile.",
        purpose="Pins expected checksums for Go module dependencies.",
        openclaw_use="Usually generated dependency state for Go tooling.",
        location="Beside `go.mod`.",
        note="Important for reproducible Go builds.",
        field_notes=[],
        cautions=[],
    ),
    "gemfile": _entry(
        identifier="basename_gemfile",
        title="Gemfile",
        category="package_metadata",
        summary="Ruby dependency manifest for Bundler.",
        purpose="Declares Ruby gems and dependency sources.",
        openclaw_use="Useful for identifying Ruby-based tools or automation.",
        location="Ruby project roots.",
        note="Often paired with `Gemfile.lock`.",
        field_notes=[],
        cautions=[],
    ),
    "gemfile.lock": _entry(
        identifier="basename_gemfile_lock",
        title="Gemfile.lock",
        category="lockfile",
        summary="Pinned Ruby gem lockfile.",
        purpose="Locks exact gem versions for Bundler-managed projects.",
        openclaw_use="Usually generated dependency state rather than user-authored logic.",
        location="Beside `Gemfile`.",
        note="Common in Ruby projects.",
        field_notes=[],
        cautions=[],
    ),
    "dockerfile": _entry(
        identifier="basename_dockerfile",
        title="Dockerfile",
        category="container_config",
        summary="Container image build recipe.",
        purpose="Defines how to build a Docker-compatible container image.",
        openclaw_use="Not OpenClaw-specific, but relevant for tool packaging, deployment, or reproducible dev environments.",
        location="Project roots or deployment directories.",
        note="High-signal file for understanding how a service or tool is meant to be built and run.",
        field_notes=[],
        cautions=[],
    ),
    "docker-compose.yml": _entry(
        identifier="basename_docker_compose_yml",
        title="docker-compose.yml",
        category="container_config",
        summary="Multi-container service orchestration file.",
        purpose="Defines related services, volumes, ports, and environment for Docker Compose.",
        openclaw_use="Often appears in local deployment or integration test setups.",
        location="Project roots or ops directories.",
        note="Usually describes how multiple services fit together locally.",
        field_notes=[],
        cautions=[],
    ),
    "compose.yml": _entry(
        identifier="basename_compose_yml",
        title="compose.yml",
        category="container_config",
        summary="Modern Compose orchestration file.",
        purpose="Defines related services, volumes, ports, and environment for local container orchestration.",
        openclaw_use="Often used the same way as `docker-compose.yml`.",
        location="Project roots or ops directories.",
        note="Compose v2 commonly uses this shorter filename.",
        field_notes=[],
        cautions=[],
    ),
    "brewfile": _entry(
        identifier="basename_brewfile",
        title="Brewfile",
        category="package_config",
        summary="Homebrew bundle manifest.",
        purpose="Declares macOS/Linux packages, casks, and taps to install through Homebrew Bundle.",
        openclaw_use="Useful on macOS-heavy environments where local tools or dependencies are provisioned via Homebrew.",
        location="Project roots or workstation setup repos.",
        note="Common in macOS bootstrap and developer workstation repos.",
        field_notes=[],
        cautions=[],
    ),
    "tsconfig.json": _entry(
        identifier="basename_tsconfig_json",
        title="tsconfig.json",
        category="package_config",
        summary="TypeScript compiler configuration.",
        purpose="Defines TypeScript compiler behavior, module resolution, and project layout.",
        openclaw_use="Useful for understanding JavaScript/TypeScript skill support code or local tools.",
        location="TypeScript project roots.",
        note="Often shapes source layout and build output folders.",
        field_notes=[],
        cautions=[],
    ),
    "makefile": _entry(
        identifier="basename_makefile",
        title="Makefile",
        category="build_automation",
        summary="Build/task automation rules for `make`.",
        purpose="Encodes named targets used to build, test, clean, or deploy a project.",
        openclaw_use="Common in source repos and local toolchains.",
        location="Project roots.",
        note="Useful for understanding standard local commands and task entrypoints.",
        field_notes=[],
        cautions=[],
    ),
    "cmakelists.txt": _entry(
        identifier="basename_cmakelists",
        title="CMakeLists.txt",
        category="build_automation",
        summary="CMake build configuration file.",
        purpose="Defines how C/C++ or multi-language builds should be configured and generated.",
        openclaw_use="Common in local native-tool directories such as model runtimes or compiled helpers.",
        location="Source roots and subdirectories in CMake projects.",
        note="Often explains large `build/` trees and compiled artifacts nearby.",
        field_notes=[],
        cautions=[],
    ),
    "readme.md": _entry(
        identifier="basename_readme_md",
        title="README.md",
        category="documentation",
        summary="Project or folder overview document.",
        purpose="Explains what a project, tool, skill, or directory is for and how to use it.",
        openclaw_use="Common in skill bundles and local tool folders.",
        location="Project or package roots.",
        note="Often the fastest human-readable way to understand an unfamiliar folder.",
        field_notes=[],
        cautions=[],
    ),
    "changelog.md": _entry(
        identifier="basename_changelog_md",
        title="CHANGELOG.md",
        category="documentation",
        summary="Version history document.",
        purpose="Records notable changes across releases or revisions.",
        openclaw_use="Useful for understanding whether a tool or skill recently changed behavior.",
        location="Project or package roots.",
        note="Often paired with semantic versioning.",
        field_notes=[],
        cautions=[],
    ),
    "license": _entry(
        identifier="basename_license",
        title="LICENSE",
        category="legal",
        summary="Software license text.",
        purpose="Declares the legal terms under which a project or package can be used and redistributed.",
        openclaw_use="Not OpenClaw-specific, but relevant for third-party skills or tool bundles.",
        location="Project roots.",
        note="Important when evaluating whether a bundled tool or skill is suitable for reuse or redistribution.",
        field_notes=[],
        cautions=[],
    ),
}


EXTENSION_REFERENCES: dict[str, dict[str, object]] = {
    ".md": _entry(
        identifier="ext_md",
        title="Markdown File",
        category="documentation",
        summary="Plain-text Markdown document.",
        purpose="Stores readable notes, docs, prompts, memory, or templates in a text-first format.",
        openclaw_use="Very common in OpenClaw workspaces because memory files, bootstrap files, skill manifests, and docs are usually Markdown.",
        location="Anywhere in docs, memory, skills, notes, or ops trees.",
        note="High-signal file type in this analyzer because Markdown often carries actual human or agent knowledge.",
        field_notes=[],
        cautions=[],
    ),
    ".txt": _entry(
        identifier="ext_txt",
        title="Text File",
        category="documentation",
        summary="Plain text file with no stronger type signal.",
        purpose="Stores unstructured notes, exports, logs, prompts, or miscellaneous text.",
        openclaw_use="Not OpenClaw-specific, but often used for quick captures, exports, or intermediary files.",
        location="Anywhere.",
        note="Meaning depends heavily on path and filename because the extension itself is generic.",
        field_notes=[],
        cautions=[],
    ),
    ".log": _entry(
        identifier="ext_log",
        title="Log File",
        category="log",
        summary="Append-oriented text log or execution trace.",
        purpose="Records runtime output, diagnostics, or event traces.",
        openclaw_use="Common around cron jobs, helper scripts, and tool wrappers.",
        location="Log folders, cache folders, or application roots.",
        note="Often more disposable than primary content, but can still be operationally important.",
        field_notes=[],
        cautions=[
            "May contain secrets, request payloads, or personal data even when the filename looks routine.",
        ],
    ),
    ".json": _entry(
        identifier="ext_json",
        title="JSON File",
        category="structured_data",
        summary="Structured text data in JSON format.",
        purpose="Stores config, metadata, exports, API payloads, or tool state in a machine-readable form.",
        openclaw_use="Extremely common in OpenClaw-adjacent tooling, skill metadata, state snapshots, and machine outputs.",
        location="Anywhere.",
        note="Path and basename usually matter more than the extension alone because JSON is used for many different roles.",
        field_notes=[],
        cautions=[],
    ),
    ".jsonl": _entry(
        identifier="ext_jsonl",
        title="JSON Lines File",
        category="structured_data",
        summary="Line-delimited stream of JSON objects.",
        purpose="Stores append-friendly logs, transcripts, event streams, or datasets.",
        openclaw_use="Common for session transcripts, cron outputs, or streaming exports.",
        location="Logs, sessions, exports, or data directories.",
        note="Often much larger and more log-like than ordinary JSON.",
        field_notes=[],
        cautions=[],
    ),
    ".yaml": _entry(
        identifier="ext_yaml",
        title="YAML File",
        category="config",
        summary="Human-edited structured config or data file.",
        purpose="Stores configuration, workflows, or structured content in a more hand-editable form than JSON.",
        openclaw_use="Common in automation, CI, or local tool config.",
        location="Project roots, config directories, and ops folders.",
        note="Often chosen for readability over strictness.",
        field_notes=[],
        cautions=[],
    ),
    ".yml": _entry(
        identifier="ext_yml",
        title="YAML File",
        category="config",
        summary="Human-edited structured config or data file.",
        purpose="Stores configuration, workflows, or structured content in a more hand-editable form than JSON.",
        openclaw_use="Common in automation, CI, or local tool config.",
        location="Project roots, config directories, and ops folders.",
        note="Often chosen for readability over strictness.",
        field_notes=[],
        cautions=[],
    ),
    ".toml": _entry(
        identifier="ext_toml",
        title="TOML File",
        category="config",
        summary="Structured config file, especially common in modern Python and Rust tooling.",
        purpose="Stores project metadata or app configuration in a concise typed format.",
        openclaw_use="Common for Python projects, tooling, and configuration-driven CLIs.",
        location="Project roots or config directories.",
        note="Often signals build metadata or tool settings rather than user-authored content.",
        field_notes=[],
        cautions=[],
    ),
    ".ini": _entry(
        identifier="ext_ini",
        title="INI File",
        category="config",
        summary="Classic section-based configuration file.",
        purpose="Stores key-value configuration in a simple legacy-friendly format.",
        openclaw_use="Common in older tools or locally configured apps.",
        location="Config directories or application roots.",
        note="Often paired with `.cfg` or `.conf` conventions.",
        field_notes=[],
        cautions=[],
    ),
    ".cfg": _entry(
        identifier="ext_cfg",
        title="Config File",
        category="config",
        summary="Generic configuration file.",
        purpose="Stores app or tool configuration in a format determined by the program using it.",
        openclaw_use="Meaning depends on nearby files and the owning tool.",
        location="Config directories or application roots.",
        note="The extension alone is generic; inspect context.",
        field_notes=[],
        cautions=[],
    ),
    ".conf": _entry(
        identifier="ext_conf",
        title="Config File",
        category="config",
        summary="Generic configuration file.",
        purpose="Stores app or tool configuration in a format determined by the program using it.",
        openclaw_use="Meaning depends on nearby files and the owning tool.",
        location="Config directories or application roots.",
        note="Especially common in Linux service and daemon configuration.",
        field_notes=[],
        cautions=[],
    ),
    ".service": _entry(
        identifier="ext_service",
        title="systemd Service Unit",
        category="service_config",
        summary="systemd service unit file.",
        purpose="Defines how a Linux service should start, stop, restart, and depend on other units.",
        openclaw_use="Relevant on Linux hosts where OpenClaw or supporting tooling is managed by systemd.",
        location="System service directories or deployment repos.",
        note="High-signal for understanding daemonized runtime behavior.",
        field_notes=[],
        cautions=[],
    ),
    ".desktop": _entry(
        identifier="ext_desktop",
        title="Desktop Entry File",
        category="desktop_metadata",
        summary="Linux desktop launcher or app metadata file.",
        purpose="Declares how an app should appear in menus and how it should be launched.",
        openclaw_use="Not OpenClaw-specific, but common on Linux desktop environments and app bundles.",
        location="Application directories or desktop-integration folders.",
        note="More UI/launcher metadata than primary content.",
        field_notes=[],
        cautions=[],
    ),
    ".url": _entry(
        identifier="ext_url",
        title="URL Shortcut File",
        category="link_reference",
        summary="Small text file that points to a URL.",
        purpose="Stores a bookmark-like pointer to a web location.",
        openclaw_use="Often encountered in exported or manually curated workspace content.",
        location="Anywhere, often in notes or reference collections.",
        note="Usually more like a bookmark than a substantive document.",
        field_notes=[],
        cautions=[],
    ),
    ".vcf": _entry(
        identifier="ext_vcf",
        title="vCard File",
        category="contact_data",
        summary="Contact-card export in vCard format.",
        purpose="Stores contacts, phone numbers, emails, and related metadata.",
        openclaw_use="Often appears in personal workspace exports or sync candidates.",
        location="Contacts exports and import/export directories.",
        note="Usually user data rather than application config.",
        field_notes=[],
        cautions=[
            "Can contain personal contact information.",
        ],
    ),
    ".ics": _entry(
        identifier="ext_ics",
        title="Calendar File",
        category="calendar_data",
        summary="Calendar/event data in iCalendar format.",
        purpose="Stores events, reminders, and calendar imports/exports.",
        openclaw_use="Often appears in calendar automation or export workflows.",
        location="Calendar exports, inboxes, or sync folders.",
        note="Usually user data rather than application config.",
        field_notes=[],
        cautions=[],
    ),
    ".csv": _entry(
        identifier="ext_csv",
        title="CSV File",
        category="tabular_data",
        summary="Delimited text table.",
        purpose="Stores rows and columns in a simple spreadsheet-friendly text format.",
        openclaw_use="Common in exports, reports, and lightweight datasets.",
        location="Data, exports, reporting, or ops folders.",
        note="Often worth previewing because semantics are not obvious from the extension alone.",
        field_notes=[],
        cautions=[],
    ),
    ".tsv": _entry(
        identifier="ext_tsv",
        title="TSV File",
        category="tabular_data",
        summary="Tab-delimited text table.",
        purpose="Stores rows and columns with tab separators.",
        openclaw_use="Common in exports or dataset-like content.",
        location="Data, exports, reporting, or ops folders.",
        note="Often used when commas inside cells would be inconvenient.",
        field_notes=[],
        cautions=[],
    ),
    ".sqlite": _entry(
        identifier="ext_sqlite",
        title="SQLite Database",
        category="database",
        summary="Local SQLite database file.",
        purpose="Stores structured relational data in an embedded single-file database.",
        openclaw_use="Common in local apps, caches, and tool state.",
        location="App data directories, caches, or local tools.",
        note="Often binary and potentially large even when the parent folder looks simple.",
        field_notes=[],
        cautions=[
            "Can contain significant user data or app state.",
        ],
    ),
    ".db": _entry(
        identifier="ext_db",
        title="Database File",
        category="database",
        summary="Generic local database or database-like file.",
        purpose="Stores structured app state, caches, or data collections.",
        openclaw_use="Meaning depends on the owning tool and nearby files.",
        location="App data, tools, or caches.",
        note="Often deserves inspection before archival or cleanup decisions.",
        field_notes=[],
        cautions=[],
    ),
    ".sqlite3": _entry(
        identifier="ext_sqlite3",
        title="SQLite Database",
        category="database",
        summary="Local SQLite database file.",
        purpose="Stores structured relational data in an embedded single-file database.",
        openclaw_use="Common in app state, caches, browser data, and local tools.",
        location="App data directories, caches, or local tools.",
        note="Semantically similar to `.sqlite`.",
        field_notes=[],
        cautions=[
            "Can contain significant user data or app state.",
        ],
    ),
    ".sql": _entry(
        identifier="ext_sql",
        title="SQL Script",
        category="database",
        summary="SQL schema, migration, or query file.",
        purpose="Defines database schema, data migrations, or ad-hoc queries.",
        openclaw_use="Common in apps and tools that rely on relational databases.",
        location="Database, migrations, or setup folders.",
        note="Often operationally meaningful because it encodes schema or data transformations.",
        field_notes=[],
        cautions=[],
    ),
    ".pdf": _entry(
        identifier="ext_pdf",
        title="PDF Document",
        category="document",
        summary="Portable Document Format file.",
        purpose="Stores fixed-layout documents such as papers, forms, manuals, or exports.",
        openclaw_use="Common in downloads, research folders, and user content.",
        location="Anywhere.",
        note="Often important user content or reference material.",
        field_notes=[],
        cautions=[],
    ),
    ".png": _entry(
        identifier="ext_png",
        title="PNG Image",
        category="media",
        summary="Raster image in PNG format.",
        purpose="Stores screenshots, assets, diagrams, or graphics.",
        openclaw_use="Common in generated-image folders, screenshots, and design assets.",
        location="Media, assets, screenshots, or exports.",
        note="Often larger than text files and more likely to be archive-oriented than sync-oriented unless obviously user-authored content.",
        field_notes=[],
        cautions=[],
    ),
    ".jpg": _entry(
        identifier="ext_jpg",
        title="JPEG Image",
        category="media",
        summary="Raster photo/image in JPEG format.",
        purpose="Stores compressed photos or other image assets.",
        openclaw_use="Common in media folders, camera exports, or web assets.",
        location="Media, photos, screenshots, or exports.",
        note="Often user content rather than configuration.",
        field_notes=[],
        cautions=[],
    ),
    ".jpeg": _entry(
        identifier="ext_jpeg",
        title="JPEG Image",
        category="media",
        summary="Raster photo/image in JPEG format.",
        purpose="Stores compressed photos or other image assets.",
        openclaw_use="Common in media folders, camera exports, or web assets.",
        location="Media, photos, screenshots, or exports.",
        note="Often user content rather than configuration.",
        field_notes=[],
        cautions=[],
    ),
    ".gif": _entry(
        identifier="ext_gif",
        title="GIF Image",
        category="media",
        summary="Animated or static GIF image.",
        purpose="Stores lightweight image assets or short loops.",
        openclaw_use="Common in downloaded assets or generated content.",
        location="Media and assets folders.",
        note="Usually content, not config.",
        field_notes=[],
        cautions=[],
    ),
    ".svg": _entry(
        identifier="ext_svg",
        title="SVG Image",
        category="media",
        summary="Vector graphic in SVG format.",
        purpose="Stores scalable diagrams, icons, or other vector graphics.",
        openclaw_use="Often doubles as both design asset and editable text file.",
        location="Assets, diagrams, exports, or docs.",
        note="Unlike raster images, SVG is text-like and can embed styles or script content.",
        field_notes=[],
        cautions=[],
    ),
    ".webp": _entry(
        identifier="ext_webp",
        title="WebP Image",
        category="media",
        summary="Modern compressed raster image.",
        purpose="Stores web-optimized images.",
        openclaw_use="Common in generated assets or downloaded media.",
        location="Media and asset folders.",
        note="Usually content, not config.",
        field_notes=[],
        cautions=[],
    ),
    ".heic": _entry(
        identifier="ext_heic",
        title="HEIC Image",
        category="media",
        summary="High-efficiency image format common on Apple devices.",
        purpose="Stores photos captured or exported from modern Apple ecosystems.",
        openclaw_use="Common in personal media workflows on macOS and iOS-adjacent setups.",
        location="Media, camera, or export folders.",
        note="Usually user content rather than configuration.",
        field_notes=[],
        cautions=[],
    ),
    ".icns": _entry(
        identifier="ext_icns",
        title="macOS Icon Asset",
        category="macos_metadata",
        summary="macOS icon resource file.",
        purpose="Stores icon assets for apps, documents, or bundles.",
        openclaw_use="Common in macOS app bundles and native packaging resources.",
        location="App bundles, design assets, or packaging folders.",
        note="Usually an asset rather than a document.",
        field_notes=[],
        cautions=[],
    ),
    ".mp3": _entry(
        identifier="ext_mp3",
        title="MP3 Audio",
        category="media",
        summary="Compressed audio file.",
        purpose="Stores music, recordings, or generated speech.",
        openclaw_use="Common in media, TTS output, or voice-note workflows.",
        location="Media, audio, or exports folders.",
        note="Usually archive-oriented unless it is primary user content.",
        field_notes=[],
        cautions=[],
    ),
    ".m4a": _entry(
        identifier="ext_m4a",
        title="M4A Audio",
        category="media",
        summary="Compressed audio file, often from Apple or mobile ecosystems.",
        purpose="Stores recordings, music, or generated speech.",
        openclaw_use="Common in personal media or capture workflows.",
        location="Media, audio, or exports folders.",
        note="Usually archive-oriented unless it is primary user content.",
        field_notes=[],
        cautions=[],
    ),
    ".wav": _entry(
        identifier="ext_wav",
        title="WAV Audio",
        category="media",
        summary="Uncompressed or lightly compressed audio file.",
        purpose="Stores high-fidelity audio, recordings, or intermediate processing inputs.",
        openclaw_use="Common in speech or transcription pipelines.",
        location="Media, audio, model, or processing folders.",
        note="Can be much larger than compressed audio formats.",
        field_notes=[],
        cautions=[],
    ),
    ".mp4": _entry(
        identifier="ext_mp4",
        title="MP4 Video",
        category="media",
        summary="Common video container format.",
        purpose="Stores screen recordings, camera videos, clips, or exports.",
        openclaw_use="Common in media, capture, or generated-content workflows.",
        location="Media, exports, or screenshots/video folders.",
        note="Often more archive-like than sync-like unless obviously active content.",
        field_notes=[],
        cautions=[],
    ),
    ".mov": _entry(
        identifier="ext_mov",
        title="QuickTime Video",
        category="media",
        summary="Video container commonly produced by Apple tools and devices.",
        purpose="Stores screen recordings or camera exports.",
        openclaw_use="Common on macOS and iOS-derived workflows.",
        location="Media, exports, and recordings folders.",
        note="Often large and archive-oriented.",
        field_notes=[],
        cautions=[],
    ),
    ".zip": _entry(
        identifier="ext_zip",
        title="ZIP Archive",
        category="archive",
        summary="Compressed archive file.",
        purpose="Packages multiple files or folders into one compressed bundle.",
        openclaw_use="Common in downloads, exports, backups, and release artifacts.",
        location="Downloads, backups, exports, or transfer folders.",
        note="Often a packaging container rather than the canonical source of truth.",
        field_notes=[],
        cautions=[
            "Contents may be more important than the archive itself.",
        ],
    ),
    ".tar.gz": _entry(
        identifier="ext_tar_gz",
        title="tar.gz Archive",
        category="archive",
        summary="Compressed tar archive.",
        purpose="Packages multiple files or folders into one archive, often for Unix-style distribution.",
        openclaw_use="Common in Linux/macOS tooling, source releases, and backups.",
        location="Downloads, backups, build artifacts, or transfer folders.",
        note="Often used for source releases or larger backup bundles.",
        field_notes=[],
        cautions=[],
    ),
    ".tgz": _entry(
        identifier="ext_tgz",
        title="tgz Archive",
        category="archive",
        summary="Short-form extension for `tar.gz` archives.",
        purpose="Packages multiple files or folders into one archive.",
        openclaw_use="Common in Unix-style tooling and release artifacts.",
        location="Downloads, backups, build artifacts, or transfer folders.",
        note="Equivalent in meaning to `tar.gz` in most contexts.",
        field_notes=[],
        cautions=[],
    ),
    ".gz": _entry(
        identifier="ext_gz",
        title="Gzip Compressed File",
        category="archive",
        summary="Single compressed file or compressed log/data stream.",
        purpose="Stores compressed data, logs, or archives.",
        openclaw_use="Common in logs, backups, downloads, and packaged artifacts.",
        location="Downloads, backups, logs, or artifacts folders.",
        note="Meaning depends on the filename before `.gz`.",
        field_notes=[],
        cautions=[],
    ),
    ".7z": _entry(
        identifier="ext_7z",
        title="7z Archive",
        category="archive",
        summary="Compressed archive in 7-Zip format.",
        purpose="Stores compressed bundles of files or folders.",
        openclaw_use="Common in downloads or cross-platform packaging.",
        location="Downloads, backups, or transfer folders.",
        note="Often chosen for higher compression.",
        field_notes=[],
        cautions=[],
    ),
    ".dmg": _entry(
        identifier="ext_dmg",
        title="macOS Disk Image",
        category="macos_package",
        summary="Disk image commonly used for macOS app distribution.",
        purpose="Packages apps or installers for macOS.",
        openclaw_use="Not OpenClaw-specific, but common in macOS downloads and application install flows.",
        location="Downloads or software archives.",
        note="Usually a distribution artifact rather than user-authored content.",
        field_notes=[],
        cautions=[],
    ),
    ".pkg": _entry(
        identifier="ext_pkg",
        title="Installer Package",
        category="macos_package",
        summary="Installer package, especially common on macOS.",
        purpose="Installs software and related assets.",
        openclaw_use="Common in local tool installation workflows on macOS.",
        location="Downloads or software archives.",
        note="Usually a distribution artifact rather than workspace content.",
        field_notes=[],
        cautions=[],
    ),
    ".deb": _entry(
        identifier="ext_deb",
        title="Debian Package",
        category="linux_package",
        summary="Debian/Ubuntu package artifact.",
        purpose="Packages software for installation on Debian-style Linux systems.",
        openclaw_use="Relevant for Linux deployment and local package distribution.",
        location="Downloads, build outputs, or package repos.",
        note="Usually a distribution artifact rather than editable source.",
        field_notes=[],
        cautions=[],
    ),
    ".rpm": _entry(
        identifier="ext_rpm",
        title="RPM Package",
        category="linux_package",
        summary="RPM package artifact.",
        purpose="Packages software for installation on RPM-based Linux systems.",
        openclaw_use="Relevant for Linux deployment and package distribution.",
        location="Downloads, build outputs, or package repos.",
        note="Usually a distribution artifact rather than editable source.",
        field_notes=[],
        cautions=[],
    ),
    ".app": _entry(
        identifier="ext_app",
        title="macOS App Bundle",
        category="macos_package",
        summary="macOS application bundle directory.",
        purpose="Contains an application plus its resources in a bundle-like folder.",
        openclaw_use="Not OpenClaw-specific, but common on macOS systems.",
        location="Applications directories or app build outputs.",
        note="Often appears as a directory even though Finder presents it like a single file.",
        field_notes=[],
        cautions=[],
    ),
    ".plist": _entry(
        identifier="ext_plist",
        title="Property List",
        category="macos_config",
        summary="Apple property-list config or metadata file.",
        purpose="Stores structured settings or metadata used by macOS and Apple apps.",
        openclaw_use="Common in macOS app bundles, preferences, and automation.",
        location="App bundles, `~/Library`, or config folders.",
        note="Can be XML or binary under the hood.",
        field_notes=[],
        cautions=[],
    ),
    ".pem": _entry(
        identifier="ext_pem",
        title="PEM Certificate or Key",
        category="credential_material",
        summary="Certificate or key material in PEM encoding.",
        purpose="Stores public certificates, private keys, or trust material for TLS and cryptographic workflows.",
        openclaw_use="Relevant for integrations, HTTPS, SSH-like tooling, and local service auth.",
        location="Credentials, certs, or config folders.",
        note="High-signal and often sensitive.",
        field_notes=[],
        cautions=[
            "Treat as sensitive until you confirm it contains only public certificate material.",
        ],
    ),
    ".crt": _entry(
        identifier="ext_crt",
        title="Certificate File",
        category="credential_material",
        summary="Certificate or trust-chain file.",
        purpose="Stores X.509 certificates for trust, TLS, or service auth.",
        openclaw_use="Relevant for service integrations and local PKI setups.",
        location="Credentials, certs, or config folders.",
        note="Often public material, but context still matters.",
        field_notes=[],
        cautions=[],
    ),
    ".cer": _entry(
        identifier="ext_cer",
        title="Certificate File",
        category="credential_material",
        summary="Certificate file in DER or related encoding.",
        purpose="Stores X.509 certificates for trust or identity.",
        openclaw_use="Relevant for service integrations and local PKI setups.",
        location="Credentials, certs, or config folders.",
        note="Usually certificate material rather than user documents.",
        field_notes=[],
        cautions=[],
    ),
    ".sh": _entry(
        identifier="ext_sh",
        title="Shell Script",
        category="script",
        summary="POSIX shell script.",
        purpose="Automates shell commands, setup, or lightweight workflows.",
        openclaw_use="Very common in skill helper scripts, tool wrappers, and local ops automation.",
        location="Scripts, hooks, build, or ops directories.",
        note="Usually operationally meaningful because it encodes executable behavior.",
        field_notes=[],
        cautions=[],
    ),
    ".zsh": _entry(
        identifier="ext_zsh",
        title="zsh Script",
        category="script",
        summary="zsh shell script.",
        purpose="Automates shell behavior using zsh-specific or POSIX-compatible syntax.",
        openclaw_use="Common on macOS-centric automation setups.",
        location="Scripts, hooks, build, or ops directories.",
        note="Often similar in role to `.sh` but with zsh-specific behavior available.",
        field_notes=[],
        cautions=[],
    ),
    ".bash": _entry(
        identifier="ext_bash",
        title="Bash Script",
        category="script",
        summary="bash shell script.",
        purpose="Automates shell behavior using bash-specific or POSIX-compatible syntax.",
        openclaw_use="Common in Linux automation and developer tooling.",
        location="Scripts, hooks, build, or ops directories.",
        note="Often similar in role to `.sh` but may rely on bash features.",
        field_notes=[],
        cautions=[],
    ),
    ".command": _entry(
        identifier="ext_command",
        title="macOS Command Script",
        category="script",
        summary="Double-clickable shell script commonly used on macOS.",
        purpose="Runs shell commands from Finder or Terminal-oriented workflows.",
        openclaw_use="Common in macOS workstation automation and bootstrap utilities.",
        location="Scripts, desktop utilities, or helper-tool folders.",
        note="Semantically similar to shell scripts, but often packaged for user-triggered execution.",
        field_notes=[],
        cautions=[],
    ),
    ".py": _entry(
        identifier="ext_py",
        title="Python Source File",
        category="source_code",
        summary="Python code file.",
        purpose="Implements scripts, CLIs, services, analysis tools, or automation logic.",
        openclaw_use="Common in local tools, helper scripts, and automation around OpenClaw.",
        location="Project roots, scripts, libraries, or tools folders.",
        note="Often directly executable or used by a CLI entrypoint.",
        field_notes=[],
        cautions=[],
    ),
    ".js": _entry(
        identifier="ext_js",
        title="JavaScript Source File",
        category="source_code",
        summary="JavaScript code file.",
        purpose="Implements scripts, CLIs, apps, or helper libraries.",
        openclaw_use="Common in third-party skill bundles and local web/tooling projects.",
        location="Project roots, scripts, lib, tests, or examples folders.",
        note="Meaning depends heavily on nearby files like `package.json` and folder names such as `lib/` or `tests/`.",
        field_notes=[],
        cautions=[],
    ),
    ".ts": _entry(
        identifier="ext_ts",
        title="TypeScript Source File",
        category="source_code",
        summary="TypeScript code file.",
        purpose="Implements typed JavaScript applications, libraries, and tooling.",
        openclaw_use="Common in modern CLIs, web tooling, and some skill bundles.",
        location="Project roots, src, scripts, lib, or tests folders.",
        note="Often compiled or executed through a Node-based toolchain.",
        field_notes=[],
        cautions=[],
    ),
    ".tsx": _entry(
        identifier="ext_tsx",
        title="TSX Source File",
        category="source_code",
        summary="TypeScript + JSX source file, often used in React-style frontends.",
        purpose="Implements UI components or app screens.",
        openclaw_use="Relevant for frontend-heavy folders or UI tooling.",
        location="Frontend source trees.",
        note="Usually part of a build pipeline rather than directly executed.",
        field_notes=[],
        cautions=[],
    ),
    ".jsx": _entry(
        identifier="ext_jsx",
        title="JSX Source File",
        category="source_code",
        summary="JavaScript + JSX source file, often used in React-style frontends.",
        purpose="Implements UI components or app screens.",
        openclaw_use="Relevant for frontend-heavy folders or UI tooling.",
        location="Frontend source trees.",
        note="Usually part of a build pipeline rather than directly executed.",
        field_notes=[],
        cautions=[],
    ),
    ".c": _entry(
        identifier="ext_c",
        title="C Source File",
        category="source_code",
        summary="C source code file.",
        purpose="Implements native code, low-level utilities, or performance-sensitive components.",
        openclaw_use="Common in compiled local tools and model/runtime dependencies.",
        location="Source trees for native code.",
        note="Often paired with build-system files and generated build artifacts nearby.",
        field_notes=[],
        cautions=[],
    ),
    ".cpp": _entry(
        identifier="ext_cpp",
        title="C++ Source File",
        category="source_code",
        summary="C++ source code file.",
        purpose="Implements native code, libraries, or performance-sensitive tooling.",
        openclaw_use="Common in local model runtimes and compiled helpers.",
        location="Source trees for native code.",
        note="Often paired with `CMakeLists.txt` and large build directories.",
        field_notes=[],
        cautions=[],
    ),
    ".go": _entry(
        identifier="ext_go",
        title="Go Source File",
        category="source_code",
        summary="Go language source file.",
        purpose="Implements Go packages, CLIs, or services.",
        openclaw_use="Common in cross-platform command-line tooling.",
        location="Go source trees.",
        note="Often paired with `go.mod`.",
        field_notes=[],
        cautions=[],
    ),
    ".h": _entry(
        identifier="ext_h",
        title="Header File",
        category="source_code",
        summary="C/C++ header file.",
        purpose="Declares interfaces, structs, macros, or APIs for native code.",
        openclaw_use="Common in native source trees.",
        location="Source trees for native code.",
        note="Usually supports `.c` or `.cpp` implementation files nearby.",
        field_notes=[],
        cautions=[],
    ),
    ".hpp": _entry(
        identifier="ext_hpp",
        title="C++ Header File",
        category="source_code",
        summary="C++ header file.",
        purpose="Declares typed interfaces or templates for C++ code.",
        openclaw_use="Common in native source trees.",
        location="Source trees for native code.",
        note="Usually supports `.cpp` implementation files nearby.",
        field_notes=[],
        cautions=[],
    ),
    ".rs": _entry(
        identifier="ext_rs",
        title="Rust Source File",
        category="source_code",
        summary="Rust language source file.",
        purpose="Implements Rust crates, libraries, and CLIs.",
        openclaw_use="Common in modern local tooling and performance-sensitive helpers.",
        location="Rust source trees.",
        note="Often paired with `Cargo.toml`.",
        field_notes=[],
        cautions=[],
    ),
    ".rb": _entry(
        identifier="ext_rb",
        title="Ruby Source File",
        category="source_code",
        summary="Ruby source file.",
        purpose="Implements Ruby scripts, gems, or automation.",
        openclaw_use="Less common than Python or shell, but still encountered in developer tooling.",
        location="Ruby source trees or automation folders.",
        note="Often paired with `Gemfile`.",
        field_notes=[],
        cautions=[],
    ),
    ".swift": _entry(
        identifier="ext_swift",
        title="Swift Source File",
        category="source_code",
        summary="Swift source file.",
        purpose="Implements Apple-platform apps, scripts, or tooling.",
        openclaw_use="Common in macOS/iOS adjacent developer environments.",
        location="Swift source trees or app projects.",
        note="Often paired with Xcode project files or Swift package manifests.",
        field_notes=[],
        cautions=[],
    ),
    ".mjs": _entry(
        identifier="ext_mjs",
        title="ES Module JavaScript File",
        category="source_code",
        summary="JavaScript source file using explicit ES module semantics.",
        purpose="Implements modern JavaScript modules.",
        openclaw_use="Common in Node-based skills and tooling.",
        location="JavaScript project trees.",
        note="Often signals modern module resolution behavior.",
        field_notes=[],
        cautions=[],
    ),
    ".cjs": _entry(
        identifier="ext_cjs",
        title="CommonJS JavaScript File",
        category="source_code",
        summary="JavaScript source file using explicit CommonJS semantics.",
        purpose="Implements Node.js modules with CommonJS behavior.",
        openclaw_use="Common in older or mixed JavaScript toolchains.",
        location="JavaScript project trees.",
        note="Often used to avoid module-format ambiguity.",
        field_notes=[],
        cautions=[],
    ),
    ".lock": _entry(
        identifier="ext_lock",
        title="Lock File",
        category="lockfile",
        summary="Lock or state-coordination file.",
        purpose="Signals in-progress work, serialized access, or pinned dependency state depending on the tool.",
        openclaw_use="Meaning depends strongly on basename and parent directory.",
        location="Caches, package managers, or runtime state directories.",
        note="Can mean either dependency pinning or concurrency control.",
        field_notes=[],
        cautions=[],
    ),
    ".pid": _entry(
        identifier="ext_pid",
        title="PID File",
        category="runtime_state",
        summary="Process identifier file.",
        purpose="Stores the PID of a running service or tool so it can be inspected or managed later.",
        openclaw_use="Common in local daemons, background services, and older Unix-style tooling.",
        location="Runtime, temp, or service-state directories.",
        note="Usually ephemeral runtime state rather than durable content.",
        field_notes=[],
        cautions=[],
    ),
    ".sock": _entry(
        identifier="ext_sock",
        title="Unix Socket",
        category="runtime_state",
        summary="Unix-domain socket endpoint.",
        purpose="Provides local inter-process communication between services and clients.",
        openclaw_use="Common in local service setups on Linux and macOS.",
        location="Runtime, temp, or service-state directories.",
        note="Usually an active IPC endpoint, not a normal document.",
        field_notes=[],
        cautions=[
            "If present live on disk, it usually represents a running service or stale runtime state.",
        ],
    ),
    ".so": _entry(
        identifier="ext_so",
        title="Shared Library",
        category="binary_artifact",
        summary="Linux shared object library.",
        purpose="Provides compiled reusable code loaded by executables or interpreters.",
        openclaw_use="Common in native toolchains, model runtimes, or packaged dependencies.",
        location="Build outputs, system libs, or app bundles.",
        note="Usually compiled artifact, not primary source code.",
        field_notes=[],
        cautions=[],
    ),
    ".dylib": _entry(
        identifier="ext_dylib",
        title="Dynamic Library",
        category="binary_artifact",
        summary="macOS dynamic library.",
        purpose="Provides compiled reusable code loaded by executables or interpreters.",
        openclaw_use="Common in native macOS tooling or bundled dependencies.",
        location="Build outputs, app bundles, or library folders.",
        note="Usually compiled artifact, not primary source code.",
        field_notes=[],
        cautions=[],
    ),
    ".bin": _entry(
        identifier="ext_bin",
        title="Binary File",
        category="binary_artifact",
        summary="Generic binary data or executable/model blob.",
        purpose="Stores compiled code, model weights, firmware, or opaque binary data.",
        openclaw_use="Meaning depends heavily on path; model folders and build trees often use `.bin`.",
        location="Models, builds, caches, or tool data folders.",
        note="Usually not directly human-readable.",
        field_notes=[],
        cautions=[],
    ),
    ".gguf": _entry(
        identifier="ext_gguf",
        title="GGUF Model File",
        category="model_artifact",
        summary="Large language model or related artifact in GGUF format.",
        purpose="Stores local model weights or quantized model variants.",
        openclaw_use="Common in local LLM workflows or model caches.",
        location="Model or tool folders.",
        note="Usually large and storage-heavy rather than sync-friendly.",
        field_notes=[],
        cautions=[],
    ),
    ".patch": _entry(
        identifier="ext_patch",
        title="Patch File",
        category="source_patch",
        summary="Unified diff or patch file.",
        purpose="Records changes to apply to source files.",
        openclaw_use="Common in code review, local patching, and packaging workflows.",
        location="Project roots, patches folders, or downloads.",
        note="Usually human-reviewable text even when generated by tooling.",
        field_notes=[],
        cautions=[],
    ),
    ".diff": _entry(
        identifier="ext_diff",
        title="Diff File",
        category="source_patch",
        summary="Text diff showing changes between files or revisions.",
        purpose="Captures proposed or observed changes in a reviewable form.",
        openclaw_use="Common in code review, exports, and patch workflows.",
        location="Project roots, review folders, or downloads.",
        note="Usually human-reviewable text.",
        field_notes=[],
        cautions=[],
    ),
    ".bak": _entry(
        identifier="ext_bak",
        title="Backup File",
        category="backup_artifact",
        summary="Backup or copy of another file.",
        purpose="Preserves an earlier revision or emergency copy.",
        openclaw_use="Often indicates manual edits, defensive copying, or tool-generated backups.",
        location="Anywhere.",
        note="Usually deserves review because it may duplicate another file and can create drift.",
        field_notes=[],
        cautions=[],
    ),
    ".tmp": _entry(
        identifier="ext_tmp",
        title="Temporary File",
        category="runtime_state",
        summary="Temporary or intermediate file.",
        purpose="Stores short-lived processing state, downloads, or intermediate results.",
        openclaw_use="Usually incidental runtime state rather than durable content.",
        location="Temp folders, caches, or working directories.",
        note="Often safe to review as disposable, but context still matters.",
        field_notes=[],
        cautions=[],
    ),
}


def all_file_type_knowledge() -> dict[str, dict[str, object]]:
    catalog: dict[str, dict[str, object]] = {}
    for key, entry in BASENAME_REFERENCES.items():
        catalog[f"basename:{key}"] = dict(entry)
    for key, entry in EXTENSION_REFERENCES.items():
        catalog[f"extension:{key}"] = dict(entry)
    return catalog


def lookup_file_type_reference(logical_path: str, extension: str | None, kind: str) -> dict[str, object] | None:
    """Return generic Linux, macOS, or project file-type guidance when no stronger reference exists."""
    if kind == "dir":
        return None
    path = PurePosixPath(logical_path.strip("/") or ".")
    basename = path.name.lower()
    if basename in BASENAME_REFERENCES:
        return BASENAME_REFERENCES[basename]

    suffixes = [suffix.lower() for suffix in path.suffixes]
    if len(suffixes) >= 2:
        compound = "".join(suffixes[-2:])
        if compound in EXTENSION_REFERENCES:
            return EXTENSION_REFERENCES[compound]

    normalized_extension = (extension or (suffixes[-1] if suffixes else "")).lower()
    return EXTENSION_REFERENCES.get(normalized_extension)
# --- End inlined module: file_type_knowledge.py ---
